Added QR format
vippsas/vipps-epayment-api pull request #52
Opened 2022-11-17 13:23 UTC by khenrichsen

Will also need to add a customerInteraction settings in the docs for this.
I didnt se any neat solutions to include QR-format and size in the request body, as the customerInteraction is an enum.

2022-11-17 13:58 UTC, tht13 commented on docs/epayment.v1.yml
> +            - QR
this is more of a compliance enum, QR could either be customer present or not present

2022-11-17 13:59 UTC, tht13 requested changes

2022-11-17 13:59 UTC, tht13 commented on docs/epayment.v1.yml
> +      name: QR-format
Agree with @ananthb86's comment in slack, this should be par of the userFlow enum, not a header

2022-11-17 14:09 UTC, khenrichsen commented on docs/epayment.v1.yml
> +      name: QR-format
Aha, wasnt aware that existed. I'll update 👍

2022-11-24 07:51 UTC, OFollan commented on docs/epayment.v1.yml
> +          description: 'The URL you should redirect the user to to continue with the payment for NATIVE_REDIRECT and WEB_REDIRECT. When user_flow is QR, a link to the QR-image (or the target url) wil
Hm. Just thinking here. For us implementing this, I think it is just as nice to just split the CreatePayment and CreateQrPayment into two separate endpoints, so that we can be more explicit in the response. Also, we don't have to create the "One Endpoint To Rule Them All", with flags and bools and ifs and buts. 

So the question is - what makes the most sense for the consumers of the API? Thoughts?

2022-12-07 15:20 UTC, cloveras commented on docs/epayment.v1.yml
> +      name: QR-format
So: Done?

2023-01-30 17:43 UTC, cloveras commented
Closingl, as this was included in another PR.

2023-01-30 17:43 UTC, closed without merging