MSISDN++
vippsas/vipps-epayment-api pull request #89
Opened 2023-02-13 09:59 UTC by cloveras

- phone number format: MSIDN
- Some formatting and minor improvements

2023-02-14 08:30 UTC, OFollan requested changes

2023-02-14 08:30 UTC, OFollan commented on docs/epayment.v1.yml
> +          format: date-time
Sadly, we can't add this line of code without introducing a hard time in our Code generator 😢 
TLDR; 
This will mark the expiresAt property as a DateTime. The dotnet framework will then deserialize to a DateTime **before** the Regex is applied to the incoming string. Ergo, we have no way of verifying the incoming date in a nice way. 

We _could_ trust the framework in the deserialization, but e.g. because of [this](https://blog.nodatime.org/2011/08/what-wrong-with-datetime-anyway.html) I don't trust DateTime at all. Ending up with DateTimes where the `DateTimeKind` is `Unspecified` is a major source of bugs (which we also had in ePayment at some point 😄 )  

So I actually dropped this line of code on purpose.
The **real** fix would be to find another generator tool, but that is a separate story..

2023-02-21 09:30 UTC, cloveras commented on docs/epayment.v1.yml
> +          format: date-time
Ah! Will fix!

2023-02-21 09:31 UTC, cloveras commented on docs/epayment.v1.yml
> +          format: date-time
```suggestion
```

2023-02-21 09:32 UTC, OFollan approved these changes

2023-02-21 09:39 UTC, merged