Examples, formatting, etc
vippsas/vipps-epayment-api pull request #93
Opened 2023-02-22 08:52 UTC by cloveras

2023-02-22 09:29 UTC, OFollan requested changes
Nice! The maxlength of IdempotencyKey needs to be changed (since this would actually block all initiate requests from Checkout, they use Guid)

2023-02-22 09:29 UTC, OFollan commented on docs/epayment.v1.yml
> +            The flow for bringing to user to the Vipps app's payment confirmation screen.
Is `´` correct in this scenario? Help native english speakers 🙈

2023-02-22 09:29 UTC, OFollan commented on docs/epayment.v1.yml
> +          example: 2019-01-01T00:00:00Z
For Date-time examples, I prefer seeing a day-of-month bigger than 12, so that we remove **any** doubt that this is YYYY-MM-DD. E.g. 2019-01-31

2023-02-22 09:29 UTC, OFollan commented on docs/epayment.v1.yml
> +          maxLength: 30
Max length should be more than 30 - as the example (and any Guid) is 36 long.
Good catch though! Currently we are missing input validation on the length of this field.

2023-02-22 09:29 UTC, OFollan commented on docs/epayment.v1.yml
> +      description: |-
Do we have this Problem object defined in a .yml file somewhere that we can just inline reference?

2023-02-22 09:29 UTC, OFollan commented on docs/epayment.v1.yml
> +        description: Requested a capture modification
Any reason this is past tense? 🤔 Doesn't
`Request a capture modification` make more sense? Same with Refund

2023-03-02 08:23 UTC, rebekaburnett commented on docs/epayment.v1.yml
> +            The flow for bringing to user to the Vipps app's payment confirmation screen.
Yes, apostrophe is right, but typo before that - "bringing the user"

2023-03-02 08:24 UTC, rebekaburnett commented on docs/epayment.v1.yml
> +        description: Requested a capture modification
Yes, that makes sense

2023-05-24 12:32 UTC, cloveras commented on docs/epayment.v1.yml
> +        description: Requested a capture modification
```suggestion
        description: Request a capture modification
```

2023-05-24 12:32 UTC, cloveras commented on docs/epayment.v1.yml
> +        description: Requested a refund modification
```suggestion
        description: Request a refund modification
```

2023-05-24 12:32 UTC, cloveras commented on docs/epayment.v1.yml
> +          example: 2019-01-01T00:00:00Z
Good point!

2023-05-24 12:33 UTC, cloveras commented on docs/epayment.v1.yml
> +      description: |-
@OFollan Yes: https://github.com/vippsas/rfc/tree/master/schemas

2023-05-24 12:35 UTC, cloveras commented on docs/epayment.v1.yml
> +          maxLength: 30
```suggestion
          maxLength: 36
```

2023-05-24 12:36 UTC, cloveras commented on docs/epayment.v1.yml
> +          example: 2019-01-01T00:00:00Z
```suggestion
          example: 2022-12-31T00:00:00Z
```

2023-05-24 12:37 UTC, cloveras commented on docs/epayment.v1.yml
> +          maxLength: 30
Changed to 36.

2023-05-24 12:47 UTC, tht13 commented on docs/epayment.v1.yml
> +        description: Request a refund modification
since this is the description of the request body then I would argue "Requested" is more grammatically correct as we are talking about the body, not the endpoint

2023-05-24 12:48 UTC, cloveras commented
Updated based on comments, resolved conflicts because this PR is old and things have happened.

2023-05-26 06:49 UTC, cloveras commented on docs/epayment.v1.yml
> +        description: Request a refund modification
```suggestion
        description: Requested refund modification
```

2023-05-26 06:49 UTC, cloveras commented on docs/epayment.v1.yml
> +          example: 'https://example.com/vipps-redirect?orderid=acme-shop-123-order123abc'
```suggestion
          example: 'https://landing.vipps.no?token=abc123'
```

2023-05-26 06:51 UTC, cloveras commented on docs/epayment.v1.yml
> +          description: The URL you should redirect the user to to continue with the payment.
```suggestion
          description: |-
            The URL you should redirect the user to to continue with the payment.
            This is the URL to the Vipps landing page.
            See: https://developer.vippsmobilepay.com/docs/vipps-developers/common-topics/vipps-landing-page/
```

2023-05-26 06:52 UTC, cloveras commented on docs/epayment.v1.yml
> +        description: Request a refund modification
Ah. I was of course right the first time. I'll never listen to anyone again.

2023-05-26 06:52 UTC, cloveras commented on docs/epayment.v1.yml
> +        description: Request a capture modification
```suggestion
        description: Requested capture modification
```

2023-06-28 09:51 UTC, rebekaburnett approved these changes

2023-06-28 11:22 UTC, cloveras commented on docs/epayment.v1.yml
> +          maxLength: 36
Updated after checking the code: https://github.com/vippsas/epayments-platform/blob/1f081f2ceb93b8e6a3867c80d2bf52a5f200819a/src/030_Presentation/010_Apis/ePayment.Api/Validation/ePayment/IdempotencyKeyValidationExtensions.cs#L29
```suggestion
          maxLength: 50
```

2023-06-28 11:23 UTC, merged